### PR TITLE
Teamq/4532 - Deactivated entries disrupt the sorting

### PR DESCRIPTION
**Pull request by alfonsoLopez1992**
```
The solution and desired transformations for deactivated entries are the following:

The databank should be extended with a field with the date for deactivated entries. In this field should be the XXX
The existing entries should be migrated so that the set modification date will be set as the deactivation date and the original modification date should be restored (maybe this date is saved in another databank field, e.g. extras or link_modifier_item).
--> If there is no way to restore the original modification date the date should be the creation date.
```

### CODE REVIEW

**Comment by alfonsoLopez1992** [comment]
@EofChris please check the code

**Review by EofChris — CHANGES_REQUESTED** [review]
Some changes to begin with:
- Please merge the three migrations into one
- You introduced a new database column like suggested in the ticket, that you called link_modifier_item_date, which I think is misleading
- Updating the modification_date when an entry get's updated must still happen

I am not sure why you went for that name, is there any reference to the link_modifier_item table?

The main problem is that the existing modification_date is used for different purposes. One is storing the last modification date an entry has been edited. The other one - which I think is a kind of misuse - is for storing the date until an entry is "deactivated" (which means only viewable and editable by the creator). If there is a specific "activate" date an entry gets unlocked the modification_date will exactly hold that. If an entry is deactivated forever, the modification_date will be "9999-00-00 00:00:00".

So to get things a little bit more clear I suggest to name the column "activation_date", which I think is not as confusing as something like "deactivated_until_date".

I was also thinking about a tinyint colum as flag for the activation state which defaults to true, but I am not sure about this right now.

**Comment by alfonsoLopez1992** [comment]
Please merge the three migrations into one -> DONE
You introduced a new database column like suggested in the ticket, that you called link_modifier_item_date, which I think is misleading -> DONE rename column to activation_date
Updating the modification_date when an entry get's updated must still happen -> Yes  this is happening

**Review by EofChris — CHANGES_REQUESTED** [review]
Please make the following changes:
- The colun annotation for the Entities in src/Entity is wrong. The new field "activationDate" is nullable
- In the DataTransformer classes please pass an instance of DateTime in setActivationDate() instead of getCurrentDateTimeInMySQL()
- For all of those entities, there is also an zzz_ equivalent. These are used when a workspace get's archived. So all entries are moved from the non zzz_ tables to the zzz_ tables. You must also add the activationDate field to those Entites in src/Entity (ZzzAnnouncement, etc...)

**Comment by alfonsoLopez1992** [comment]
@EofChris please check the code, comments resolved

**Review by EofChris — APPROVED** [review]
I fixed some formatting, improved imports and fixed the merge conflict.

**Pull request merged**
