### PR TITLE
Teamq/4595 -  The answer form should always be visible

### PR DESCRIPTION
**Pull request by alfonsoLopez1992**
```
The answer form (to write an answer to a discussion) in a discussion should always be displayed. That means if you click on a discussion in the list view the discussion will open with the form already showing so that you can answer directly without having to use the "choose action" menu.

The action "answer" should be removed from the "choose action" menu on the top of the entry. 

Also the button to submit the answer should be called 
English: "Answer" 
Deutsch: "Antworten" ``
```

### CODE REVIEW

**Comment by alfonsoLopez1992** [comment]
@EofChris please check the code

**Review by EofChris — CHANGES_REQUESTED** [review]
You introduced a new controller action DiscussionController::createArticleInitialAction(). It looks like a copy of the DiscussionController::createArticleAction() we already have. Is there any reason for the new action? Can you reuse the existing one?

**Comment by alfonsoLopez1992** [comment]
@EofChris please check the code

**Review by EofChris — CHANGES_REQUESTED** [review]
Openening the detail view will no always display the create answer form, which is good, but it currently has a major side-effect. The page is in "edit"-mode which - along other things - disables selecting any action.

Also you basically made a copy of onClickEdit() in edit.js for discussions witch is very repetitive.

**Comment by alfonsoLopez1992** [comment]
Closed becouse, need branch 4631

**Pull request closed without merging**
