### PR TITLE
Resolved bug - Error when viewing a deactivated entry without the aut…

### PR DESCRIPTION
**Pull request by alfonsoLopez1992**
The desired behavior is that they cannot click on the link (just like they cannot click in it in the list of the rubric, e. g. screenshot) and that instead of the title it should say 
English: (Deactivated entry) 
German: (Deaktivierter Eintrag)

### CODE REVIEW

**Comment by alfonsoLopez1992** [comment]
@EofChris please check the pull request.

**Review by EofChris — CHANGES_REQUESTED** [review]
In the rubric's feed (for example templates/material/feed.html.twig) there is the same check in line 45:

```
{% if is_granted('ITEM_SEE', material.itemId) %}
    <a href="{{ path('app_material_detail', {'roomId': roomId, 'itemId': material.itemId}) }}">{{ material.title|decodeHtmlEntity }}</a>
{% else %}
    {{ material.title|decodeHtmlEntity }}
{% endif %}
```

I think instead of creating an additional voter logic we should investigate why **ITEM_SEE** is not working in the search result feed. Can you try to find out why it is not working there?

This might help you track down the problem:
- Check for **ItemVoter::SEE** will call `maySee()` on cs_item (or any child).
- `cs_item::maySee` does already check for not activated items

I guess the problem is the context, because the global search will contain entries from different rooms. I suspect the check in `cs_item::maySee` line 1616 to be problematic.

**Review by EofChris — CHANGES_REQUESTED** [review]
I did a quick test if we can use the logic we already have, since we already check for `ITEM_SEE` in search/feed.html.twig.

Please try:
- Remove the ItemVoter::SEARCH logic and canViewSearch method
- use the old `ITEM_SEE` check in feed.html.twig
- Replace cs_item::1616 with `if ($userItem->isUser() && $userItem->getContextID() === $this->getContextID()) {`

The main thing here is, that the users context id is now checked against the items context id and not the environment one's. So it's not "enough" to be moderator of the current room, but of the items room.

We'll have to check if this breaks something else, but it might be a better solution.

**Comment by alfonsoLopez1992** [comment]
@EofChris please check the code.

**Review by EofChris — APPROVED** [review]

**Pull request merged**
